name: mac
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15-intel
    
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Core Configuration
      run: |
        chmod +x configure.sh
        ./configure.sh "${{ secrets.VNC_USER_PASSWORD }}" "${{ secrets.VNC_PASSWORD }}"

    - name: Keep Active
      run: |
        echo "Server is running! Check the logs above for your Pinggy TCP address."
        sleep 21600
